/*
    Copyright (c) 2018 Piotr Doan. All rights reserved.
*/

#pragma once

#include "Precompiled.hpp"

/*
    Build

    Retrieves and stores information generated by the build system.
    Will not work if the executable is outside of the build directory.
*/

namespace Build
{
    // Loads information generated by the build system.
    void Initialize();

    // Gets the working directory retrieved from the build system.
    std::string GetWorkingDir();

    // Gets the source directory retrieved from the build system.
    std::string GetSourceDir();
}
