/*
    Copyright (c) 2018 Piotr Doan. All rights reserved.
*/

#pragma once

#include <string>

/*
    Build

    Stores information generated and retrieved from the build system.
*/

namespace Build
{
    // Returns the main binary directory generated by CMake.
    std::string GetBuildDir();

    // Returns the directory of engine's include headers.
    std::string GetIncludeDir();

    // Returns the directory of engine's source code.
    std::string GetSourceDir();

    // Returns the number of changes from the root of commit tree.
    std::string GetChangeNumber();

    // Returns the short hash of current commit.
    std::string GetChangeHash();

    // Returns the date of current commit.
    std::string GetChangeDate();

    // Returns the current branch name.
    std::string GetBranchName();
}
