/*
    Copyright (c) 2018 Piotr Doan. All rights reserved.
*/

#pragma once

#include <string>

/*
    Build

    Stores information generated and retrieved from the build system.
*/

namespace Build
{
    // Initializes build related info.
    void Initialize();

    // Gets the working directory.
    std::string GetWorkingDir();

    // Gets the main binary directory generated by CMake.
    std::string GetBuildDir();

    // Gets the directory of engine's include headers.
    std::string GetIncludeDir();

    // Gets the directory of engine's source code.
    std::string GetSourceDir();

    // Gets the number of changes from the root of commit tree.
    std::string GetChangeNumber();

    // Gets the short hash of current commit.
    std::string GetChangeHash();

    // Gets the date of current commit.
    std::string GetChangeDate();

    // Gets the current branch name.
    std::string GetBranchName();
}
