/*
    Copyright (c) 2018 Piotr Doan. All rights reserved.
*/

#pragma once

#include <string>

/*
    Build

    Retrieves and stores information generated by the build system.
    Will not work if the executable is outside of the build directory.
*/

namespace Build
{
    // Loads information generated by the build system.
    void Initialize();

    // Gets the working directory.
    std::string GetWorkingDir();

    // Gets the include directory.
    std::string GetIncludeDir();

    // Gets the source directory.
    std::string GetSourceDir();
}
